Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
DCC-SW: Released modules (2020-aug/XeonE5-2660v3)
Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
DCC-SW: Released modules (2020-aug/XeonE5-2660v3)
Modules Release 4.3.0 (2019-07-26)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
python3: can't open file 'fepo4_1li_sub.py': [Errno 2] No such file or directory
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52385,1],0]
  Exit code:    2
--------------------------------------------------------------------------
